import {tree} from "./bst.js";
import randomArray from "./randomArray.js";
const myTree = tree();
const array = randomArray(20);
myTree.buildTree(array);
myTree.prettyPrint();
console.log(myTree.isBalanced());
myTree.insert(510);
myTree.insert(520);
myTree.insert(530);
myTree.insert(540);
myTree.prettyPrint();
console.log(myTree.isBalanced());
myTree.rebalance();
myTree.prettyPrint();
console.log(myTree.isBalanced());